// Copyright 2025-2026 School of Integrated Circuits, Peking University
// SPDX-License-Identifier: Apache-2.0 WITH SHL-2.1
//
// Licensed under the Solderpad Hardware License v 2.1 (the "License"); you may
// not use this file except in compliance with the License, or, at your option,
// the Apache License version 2.0. You may obtain a copy of the License at
// https://solderpad.org/licenses/SHL-2.1/
//
// Stand-in for the clocking wrapper `clk_div` that the FPGA branch of
// soc_noc.sv instantiates. The real wrapper is generated by the FPGA tool flow
// and is not part of this repository. This pass-through stub is used only by
// verification/run_dco_checks.py to compile the FPGA branch of the extracted
// clock slice; it is not part of filelist.f and is not a clock divider model.
module clk_div (
  input  wire sys_clk_i,
  input  wire resetn,
  output wire sys_clk_div,
  output wire locked
);
  assign sys_clk_div = sys_clk_i;
  assign locked      = resetn;
endmodule
